###
GET http://localhost:3000/api

###
POST http://localhost:3000/api
content-type: application/json

{
  "name":"test-3",
  "meaning":"test",
  "fixed":false
}

###
PATCH  http://localhost:3000/api/dcbaf064-da80-4b99-b414-3e96c8b8d49e
content-type: application/json

{
  "fixed":true
}



###
DELETE  http://localhost:3000/api/dcbaf064-da80-4b99-b414-3e96c8b8d49e