###
GET http://localhost:3000/api

###
POST http://localhost:3000/api
content-type: application/json

{
  "name":"test-2",
  "meaning":"test"
}

###
DELETE  http://localhost:3000/api/a4b18b5b-926f-450d-bf1f-fdc42c0fd690
