#!/bin/bash

message=$1


npm run lint 
status=$?
if [ "$status" != 0 ]; then 
  echo -e "Erro no lint"
  exit $status
fi

npm run build
status=$?
if [ "$status" != 0 ]; then 
  echo -e "Erro no build"
  exit $status
fi

git add .
git commit -m "$message"
git push

